brentyi/tyro

pyproject.toml, tests/test_dcargs.py, tyro/_cli.py
=> Add `return_unknown_args` to `tyro.cli`

tests/test_dcargs.py, tests/test_helptext.py, tyro/_docstrings.py, tyro/_fields.py, tyro/_instantiators.py
This solves most of the issues outlined in #36 and #37. Specifically,
1. Exactly like #37 it converts `os.PathLike` to `pathlib.Path`.
2. Additionally, if an object acts as `PathLike`, i.e., implements `os.PathLike` and is a type converter, i.e., `(arg: Union[str, Any]) -> T` then Tyro will parse this object as the "leaf node". This allows for custom `PathLike` objects like `epath.Path`.
3. Allows for recursing on objects that implement `__new__` and not `__init__`. One such object is `pathlib.Path` but there could be others out there.
Is there an argument to be made that any callable with a single positional argument that is `Union[str, Any]` should be treated as a leaf node? Or could there be a marker to specifically enable this functionality? If I remove the custom check for `PathLike` …
=> Add support for PathLike classes & objects with __new__ but no __init__

tests/test_helptext.py, tyro/_argparse_formatter.py
Previously, if a `str` type argument's default value contains `%`, the `--help` action fails.  Reproducible example:
```bash
$ cat >percent-char.py <<EOF
import tyro
from dataclasses import dataclass
@dataclass
class A:
name: str = "%"
def main(args: A):
print(args.name)
tyro.cli(main)
EOF
$ python percent-char.py --help
[...truncated...]
File "/.../lib/python3.9/argparse.py", line 630, in _expand_help
return self._get_help_string(action) % params
ValueError: unsupported format character ')' (0x29) at index 29
```
This commit fixes this and updates the test for default help text to cover this case.
=> Fix `%` character as default str argument in dataclass

docs/source/examples/04_additional/02_dictionaries.rst, examples/04_additional/02_dictionaries.py, tests/test_conf.py, tests/test_errors.py, tests/test_nested.py, tyro/_arguments.py, tyro/_docstrings.py, tyro/_fields.py, tyro/_instantiators.py, tyro/conf/__init__.py, tyro/conf/_markers.py
Addresses #46 by introducing `tyro.conf.UseAppendAction`, which sets `action="append"` for variable-length sequence types. If we want to populate `x = [1, 2, 3]`, `x: List[str]` expects `--x 1 2 3`; `x: UseAppendAction[List[str]]` will expect `--x 1 --x 2 --x 3`.
Basic usage:
```python
from typing import Tuple
import tyro
from tyro.conf import UseAppendAction
def main(filter: UseAppendAction[Tuple[str, ...]]) -> None:
"""Main script.
Args:
filter: Filter to apply.
"""
print(filter)
tyro.cli(main)
```
And resulting help message:
=> Append action for variable-length containers

tests/test_boolean_optional.py, tests/test_helptext.py, tyro/_argparse_formatter.py, tyro/_arguments.py
New default behavior for booleans with defaults, as suggested in #48.
We backport `argparse.BooleanOptionalAction`, resulting in both `--flag` and `--no-flag` being created by default:
=> More predictable boolean flag behavior

tyro/_arguments.py
```
import tyro
def args(flag: bool = True):
pass
tyro.cli(args)
```
results in 
```
(openrlbenchmark-py3.9) ➜  openrlbenchmark git:(offline) ✗ python tyro_test.py --no-flag
{'--no-flag'}
(openrlbenchmark-py3.9) ➜  openrlbenchmark git:(offline) ✗ 
```
=> Remove debugging print statement

docs/source/examples/03_config_systems/01_base_configs.rst, examples/03_config_systems/01_base_configs.py, tests/test_collections.py, tests/test_dcargs.py, tests/test_dict_namedtuple.py, tests/test_helptext.py, tests/test_positional_ignore_py37.py, tyro/__init__.py, tyro/_calling.py, tyro/_instantiators.py, tyro/_strings.py
Hi Brent, thanks for your kind suggestions on issue #56!
This commit makes it possible to set Tuple, Dict, and Union to empty by passing in `-` in the command line as the only argument. The functionality is tested with an additional test in `test_dcargs.py`.
Note that I'm currently using `-` instead of `*` as the indicator of an empty container because `*` is usually expanded into the file names in the working directory, in which case the user has to pass in `"*"` to disable the expansion.
For the example below,
```python
from dataclasses import dataclass
@dataclass()
class BaseConfig:
x: tuple[str, ...] = ("a", "b", "c")
print(tyro.cli(BaseConfig).x)
```
we can now set the item `x` to empty with the following command:
```shell
python main.py --x -
```
Output: …
=> Support setting Tuple, Dict, and Union to empty in the command line.

tests/test_conf.py, tyro/_fields.py, tyro/conf/__init__.py, tyro/conf/_markers.py
=> Add conf.PositionalRequiredArgs

tests/helptext_utils.py, tests/test_dcargs.py, tests/test_dict_namedtuple.py, tests/test_helptext.py, tyro/_arguments.py, tyro/_cli.py, tyro/_strings.py
Previously: `field_a` => `--field-a`.
After setting `use_underscores=True`: `field_a` => `--field_a`
Addresses #75!
cc @vwxyzjn
=> Add `use_underscores` option

pyproject.toml, tests/test_conf.py, tests/test_py311_generated/test_conf_generated.py, tyro/_fields.py
Resolves an issue exposed by #89, where:
```diff
import tyro
+import dataclasses
def checkout(branch: str) -> None:
"""Check out a branch."""
print(f"{branch=}")
def commit(message: str, all: bool = False) -> None:
"""Make a commit."""
print(f"{message=} {all=}")
+@dataclasses.dataclass
+class Arg:
+    foo: int = 1
+
tyro.cli(
Union[
Annotated[
Any,
tyro.conf.subcommand(name="checkout", constructor=checkout),
],
Annotated[
Any,
tyro.conf.subcommand(name="commit", constructor=commit),
],
+            Arg,
]
)
```
should produce _three_ subcommands, `checkout`, `commit`, and `arg`. The type narrowing logic was previously failing and only producing `checkout` and `commit`.
=> Fix type narrowing edge case for unions

tests/test_helptext.py, tests/test_py311_generated/test_helptext_generated.py, tests/test_py311_generated/test_nested_generated.py, tyro/_argparse_formatter.py
=> Account for indent in subcommand helptext wrapping

tests/test_collections.py, tests/test_mixed_unions.py, tests/test_new_style_annotations_min_py39.py, tests/test_py311_generated/test_collections_generated.py, tests/test_py311_generated/test_mixed_unions_generated.py, tests/test_py311_generated/test_nested_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py39_generated.py, tyro/_calling.py, tyro/_cli.py, tyro/_fields.py, tyro/_parsers.py, tyro/_resolver.py, tyro/_strings.py, tyro/_subcommand_matching.py
Closes #42
This:
```python
import dataclasses
from typing import Union
import tyro
@dataclasses.dataclass
class Args:
y: str
def main(x: Union[int, Args]) -> None:
print(x)
tyro.cli(main)
```
Now produces:
=> Add support for mixed unions

tests/conftest.py, tests/test_base_configs_nested.py, tests/test_errors_new_annotations.py, tests/test_helptext.py, tests/test_py311_generated/test_conf_generated.py, tyro/_fields.py, tyro/_instantiators.py, tyro/_resolver.py
Improves error from https://github.com/huggingface/trl/issues/1032
As an example in Python 3.8, this:
```python
from __future__ import annotations
def main(x: list[int]) -> None:
...
import tyro
tyro.cli(main)
```
will now print:
```
Error calling typing.get_type_hints() on <function main at 0x1008261f0>! You may be using a standard collection as a generic, like `list[T]` or `tuple[T1, T2]`. To support Python versions lower than 3.9, you need to using `typing.List[T]` and `typing.Tuple[T1, T2]`.
```
=> Improve PEP 585/604 annotation errors for older versions of Python

pyproject.toml, tests/test_pydantic.py, tyro/_fields.py
Default values are now properly parsed when an instance of a `pydantic.BaseModel` is provided.
```python
import pydantic
import tyro
class Config(pydantic.BaseModel):
a: int = 1
def main(config: Config = Config(a=2)) -> None:
pass
tyro.cli(main)
```
```bash
$ python a.py -h
usage: a.py [-h] [--config.a INT]
╭─ arguments ───────────────────────────────────────────╮
│ -h, --help            show this help message and exit │
╰───────────────────────────────────────────────────────╯
╭─ config arguments ────────────────────────────────────╮
│ --config.a INT        (default: 2)                    │  # <-- good!
╰───────────────────────────────────────────────────────╯
```
This fixes #107 and fixes #108.
=> Fix default values in Pydantic

examples/02_nesting/01_nesting.py, pyproject.toml, src/tyro/_argparse_formatter.py, src/tyro/_parsers.py, tests/test_errors.py, tests/test_helptext.py, tests/test_missing.py, tests/test_nested.py, tests/test_py311_generated/test_errors_generated.py, tests/test_py311_generated/test_helptext_generated.py, tests/test_py311_generated/test_missing_generated.py, tests/test_py311_generated/test_nested_generated.py, tests/test_py311_generated/test_union_from_mapping_generated.py, tests/test_union_from_mapping.py
Addresses #113!
Before:
After:
The shorter usage is enabled when we have >4 arguments. Some more examples:
=> More succinct usage when a lot of options are present

src/tyro/_parsers.py
Fixes #123.
An unintended side-effect of #118 introduced a regression that broke the `tyro.cli(description=...)` field for hierarchical configs. This was due to an extraneous setting of the `argparse.ArgumentParser.description` field, which was causing the description to be set by the description of a leaf node in the tree.
The description was initially set in the `.apply()` method here: https://github.com/brentyi/tyro/blob/30803e8a4ee871693f7b021be84265780ddc0146/src/tyro/_parsers.py#L201
Later, there is a call into the `.apply_args()` method that sets the description again:
https://github.com/brentyi/tyro/blob/30803e8a4ee871693f7b021be84265780ddc0146/src/tyro/_parsers.py#L241
This is problematic after #118 because we now recurse into the `.apply_args()` method: …
=> Fix: `tyro.cli` description

src/tyro/_arguments.py, src/tyro/_fields.py, src/tyro/conf/_confstruct.py, tests/test_conf.py
=> Support overriding behavior hint in argument helptext

src/tyro/_resolver.py, tests/test_new_style_annotations_min_py310.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py310_generated.py
These should be treated the same in Python >=3.10, but are unfortunately very different objects at runtime. Just accounted for this.
Addresses #164.
=> Fix inconsistency between `type[T]` and `typing.Type[T]` annotations

pyproject.toml, src/tyro/_instantiators.py, src/tyro/conf/__init__.py, src/tyro/conf/_markers.py, tests/test_dcargs.py, tests/test_py311_generated/test_dcargs_generated.py
* Add configuration marker: SelectionFromEnumValues
* Refactor instantiator production logic for types with automatically-populated choices. Encapsulation to keep related variables tracked togther.
Resolves #166 .
@brentyi : All linter checks and tests are passing. Not sure if you want anything additional for documentation; looks like you have an automatic generator which I did not look closely at.
Also, manual proof that it works as described and intended:
```python
>>> import dataclasses, enum, typing_extensions, tyro
>>> class Formats( enum.StrEnum ):
...     JSON = enum.auto( )
...     PRETTY = enum.auto( )
...
>>> @dataclasses.dataclass
... class Args:
...     format: typing_extensions.Annotated[ Formats, tyro.conf.SelectFromEnumValues ] = Formats.PRETTY
...
>>> tyro.cli( Args, args …
```
=> Feature: Markers: SelectionFromEnumValues

examples/01_basics/01_functions.py, src/tyro/_cli.py, tests/helptext_utils.py
=> Fix `--tyro-write-completion` when `use_underscores=True`

src/tyro/extras/_subcommand_cli_from_dict.py, tests/test_errors.py
Ran into this issue while trying to `torchrun` an entrypoint which uses `tyro.extras.subcommand_cli_from_dict`. 
My thinking is that the API should be as close as possible to `tyro.cli`?
=> Allow subcommand_cli_from_dict to specify console_outputs

src/tyro/extras/_subcommand_app.py, src/tyro/extras/_subcommand_cli_from_dict.py
=> More complete wrappers in `tyro.extras` (for `torchrun`, etc)

src/tyro/_fields.py, src/tyro/_instantiators.py, src/tyro/_parsers.py, src/tyro/_resolver.py, src/tyro/_strings.py, src/tyro/_subcommand_matching.py, src/tyro/extras/_serialization.py, src/tyro/extras/_subcommand_cli_from_dict.py, tests/test_new_style_annotations_min_py312.py, tests/test_py311_generated/test_errors_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py312_generated.py
First PR for issues uncovered by #177.
Type aliases were not being correctly resolved for reading metadata introduced by `typing.Annotated`:
```python
type AnnotatedBasic = Annotated[int, tyro.conf.arg(name="basic")]
def test_annotated_alias():
@dataclass(frozen=True)
class Container:
a: AnnotatedBasic
assert tyro.cli(Container, args="--basic 1".split(" ")) == Container(1)
```
=> Fix edge case when combining PEP 695 aliases with `typing.Annotated[]`

src/tyro/_fields.py, src/tyro/_resolver.py, tests/test_new_style_annotations_min_py312.py
This should fix the example from #177, which is now included in the test cases.
=> Fix generic aliases generated by Python 3.12 `type` statements

docs/source/index.md, docs/source/supported_types.md, pyproject.toml, src/tyro/__init__.py, src/tyro/_calling.py, src/tyro/_fields.py, src/tyro/_instantiators.py, src/tyro/_parsers.py, src/tyro/_resolver.py, src/tyro/_strings.py, src/tyro/_subcommand_matching.py, src/tyro/extras/_serialization.py, tests/test_nested.py, tests/test_new_style_annotations_min_py312.py, tests/test_py311_generated/test_nested_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py312_generated.py
=> Fix edge cases associated with nested/recursive PEP 695 aliases

src/tyro/_cli.py, src/tyro/_docstrings.py, src/tyro/_fields.py, src/tyro/_parsers.py, src/tyro/_resolver.py, src/tyro/_strings.py, src/tyro/_subcommand_matching.py, tests/test_nested.py, tests/test_new_style_annotations_min_py312.py, tests/test_py311_generated/test_nested_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py312_generated.py
Patterns like this now work:
```python
@dataclass(frozen=True)
class Container[T]:
a: T
tyro.cli(
Container[Container[bool] | Container[Literal["1", "2"]]]
)
```
Also improved matching logic when the `default=` argument is specified.
=> Support cyclic generics

src/tyro/_fields.py, tests/test_py311_generated/test_pydantic_generated.py, tests/test_pydantic.py
Older versions of pydantic didn't support `typing.Annotated`, since `typing.Annotated` didn't exist yet. I added a workaround for this.
Fixes #186
=> `typing.Annotated` workaround for pydantic v1

src/tyro/_cli.py, src/tyro/_strings.py, src/tyro/extras/_subcommand_app.py, tests/test_decorator_subcommands.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_decorator_subcommands_generated.py, tests/test_py311_generated/test_pydantic_with_newtype_generated.py, tests/test_pydantic_with_newtype.py
Previously, this was only being applied to subcommand names generated from union types and to argument names.
Fixes #205
=> Apply `use_underscores` to decorator-based subcommand names

pyproject.toml, src/tyro/_arguments.py, src/tyro/_calling.py, src/tyro/_fields.py, src/tyro/_parsers.py, src/tyro/constructors/_primitive_spec.py, src/tyro/constructors/_registry.py, src/tyro/constructors/_struct_spec.py, tests/test_nested.py, tests/test_py311_generated/test_nested_generated.py
- The `instantiate=` function passed into `StructConstructorSpec` is now correctly used.
- Multiple constructor registries can now be active simultaneously.
- Simpler logic for determining whether a type is a primitive or a struct.
=> Fix instantiation edge cases for custom struct types

src/tyro/_arguments.py, src/tyro/_fields.py, src/tyro/_parsers.py, tests/test_conf.py, tests/test_py311_generated/test_conf_generated.py
Fixes #216; this is unlikely to be useful, but there's no reason why (in principle) it shouldn't work.
=> Support recursive argument suppression

src/tyro/_argparse_formatter.py, src/tyro/_arguments.py, src/tyro/_calling.py, src/tyro/_cli.py, src/tyro/_parsers.py, src/tyro/conf/_confstruct.py, tests/test_collections.py, tests/test_conf.py, tests/test_errors.py, tests/test_py311_generated/test_collections_generated.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_errors_generated.py
- Show overridden metavars in error messages when available (fixes #218)
- Show aliases in error messages
=> Improve error messages when tyro.conf.arg() options are set

README.md, docs/source/index.md, src/tyro/_fields.py, src/tyro/_parsers.py, src/tyro/_resolver.py, tests/test_conf.py, tests/test_py311_generated/test_conf_generated.py
Now fixed:
Example of one bug we had:
```python
from dataclasses import dataclass
import tyro
@dataclass(frozen=True)
class Container[T]:
value: T | bool
def main(
container: Container[int] | Container[str] = Container("default string"),
) -> None:
print(container.value)
tyro.cli(main, config=(tyro.conf.AvoidSubcommands,))
```
The help that we expect and now get is:
```
usage: test.py [-h] [--container.value STR|{True,False}]
╭─ options ─────────────────────────────────────────╮
│ -h, --help        show this help message and exit │
╰───────────────────────────────────────────────────╯
╭─ container options ───────────────────────────────╮
│ --container.value STR|{True,False}                │
│                   (default: 'default string')     │ …
```
=> Fix subcommand edge cases associated with generics, `tyro.conf.Suppress`, `tyro.conf.AvoidSubcomands`

src/tyro/_argparse_formatter.py, src/tyro/constructors/_struct_spec.py, tests/test_nested.py
@mirceamironenco this fixes the second bug you pointed out in #221, which is caused by a bug introduced in `0.9.1`. I also added your example to the tests to prevent regressions; I really appreciate the succinct reproduction instructions!
=> Fix subcommand matcher when `tyro.conf.subcommand` is used

src/tyro/_calling.py, src/tyro/_cli.py, src/tyro/_parsers.py, src/tyro/conf/_markers.py, tests/test_conf.py, tests/test_py311_generated/test_conf_generated.py
=> Support optional subcommands under `tyro.conf.ConsolidateSubcommandArgs`

examples/06_custom_constructors/04_struct_registry.py, src/tyro/__init__.py, src/tyro/_fields.py, src/tyro/_parsers.py, src/tyro/conf/_confstruct.py, src/tyro/constructors/_struct_spec.py, tests/test_base_configs_nested_exclude_py313.py, tests/test_conf.py, tests/test_py311_generated/test_base_configs_nested_exclude_py313_generated.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_nested_generated.py
Default values specified in field declarations now always take precedence over default values specified in annotations. Updated tests + docs to reflect this.
cc #221
=> Consistent behavior for implicit and explicit selection of optional subcommands

docs/source/examples/custom_constructors.rst, examples/06_custom_constructors/04_struct_registry.py, src/tyro/__init__.py, src/tyro/_fields.py, src/tyro/_parsers.py, src/tyro/conf/_confstruct.py, src/tyro/constructors/_primitive_spec.py, src/tyro/constructors/_struct_spec.py, tests/test_collections.py, tests/test_nested.py, tests/test_py311_generated/test_collections_generated.py, tests/test_py311_generated/test_nested_generated.py
Regression in 0.9.2, cc https://github.com/nerfstudio-project/nerfstudio/pull/3567
=> Fix `list[dict]` regression

docs/source/whats_supported.rst, src/tyro/_arguments.py, src/tyro/_resolver.py, tests/test_generics_and_serialization.py, tests/test_py311_generated/test_generics_and_serialization_generated.py
This pattern is now supported:
```python
import tyro
class Config[T: str | int]:
def method(self, x: T) -> T:
return x
tyro.cli(Config[int]().method)
```
We also handle the case where methods are inherited; this fixes #233.
=> Support methods bound to generic classes

.github/workflows/pytest.yml, src/tyro/_resolver.py, tests/test_new_style_annotations_min_py39.py, tests/test_py311_generated/test_new_style_annotations_min_py39_generated.py
=> Workaround for `__type_params__` bug in Python 3.12.0

src/tyro/_fields.py, src/tyro/_resolver.py, tests/test_attrs.py, tests/test_dcargs.py, tests/test_new_style_annotations_min_py312.py, tests/test_py311_generated/test_attrs_generated.py, tests/test_py311_generated/test_dcargs_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py312_generated.py
Our logic for retrieving type hints + resolving type parameters was following a depth-first order instead of C3 linearization.
This causes problems for overriding fields in specific "diamond" inheritance patterns. I added some to the tests.
I also noted some inconsistent behavior. In this example we end up with the type annotation from `A` but the default value from `C`:
```python
@dataclasses.dataclass(frozen=True)
class A:
field: int | str = 5
@dataclasses.dataclass(frozen=True)
class B(A):
pass
@dataclasses.dataclass(frozen=True)
class C(A):
field: int = 10
@dataclasses.dataclass(frozen=True)
class D(B, C):
pass
helptext = get_helptext_with_checks(D)
assert "5" in helptext
assert "10" not in helptext
assert "INT|STR" not in helptext
```
This is really unfortunate, but the root cause …
=> Correct MRO traversal for inherited fields

src/tyro/_argparse_formatter.py, src/tyro/_arguments.py, tests/test_conf.py, tests/test_new_style_annotations_min_py39.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_new_style_annotations_min_py39_generated.py
"Append" actions were broken for abstract sequences (`typing.Sequence`, `collections.abc.Sequence`) in the 0.9.0 refactor.
Fixes #244
=> Fix `tyro.conf.UseAppendAction` + abstract `Sequence` annotations

src/tyro/_arguments.py, tests/test_conf.py, tests/test_errors.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_errors_generated.py
=> Show flag aliases before auto-generated names in helptext

src/tyro/conf/_confstruct.py, tests/helptext_utils.py
=> Reduce `Unknown` types at API boundaries

docs/source/helptext_generation.md, src/tyro/_docstrings.py, src/tyro/_fields.py, src/tyro/conf/__init__.py, src/tyro/conf/_markers.py, src/tyro/constructors/_struct_spec.py, tests/test_conf.py, tests/test_py311_generated/test_conf_generated.py
Need to update docs, add tests.
Fixes #242
=> Add flag to turn off helptext generation from comments

src/tyro/_arguments.py, src/tyro/conf/__init__.py, src/tyro/conf/_markers.py, tests/test_boolean_optional.py
Hi, I really appreciate your work. I am a happy user since months when I did a study, comparing over 25+ CLI parsing projects and tyro was the best.
I am trying to port a project with a lot of options to tyro. However, there are some things that look bad: I'd really like to turn off boolean negation. As I have many options with aliases, the flag namespace gets really polluted. As all of the flags are off by default, I really need only the positive flag.
Here, I propose an option to do this behaviour. I've added a test as well. How should I edit the code so that it is convenient for the tyro code base please?
=> Add flag to turn off boolean negation

src/tyro/_parsers.py, tests/test_conf.py, tests/test_helptext.py, tests/test_py311_generated/test_boolean_optional_generated.py, tests/test_py311_generated/test_conf_generated.py, tests/test_py311_generated/test_helptext_generated.py
#252 reverted the helptext grouping behavior discussed in #183 for when `tyro.conf.arg(name="")` is used. I restored this. The groupings that motivated #252 should be unaffected.
=> Restore helptext behavior for erased argument names + tests

src/tyro/_calling.py, tests/test_custom_constructors.py, tests/test_py311_generated/test_custom_constructors_generated.py
Custom constructors were not being called correctly when:
- A variable-length argument was defined
- The argument was set to positional
- A length-0 input was passed in
cc #257
=> Fix custom constructor edge case for variable-length positional arguments

src/tyro/_singleton.py, src/tyro/constructors/_struct_spec.py, tests/test_missing.py
- More consistent behavior when `tyro.MISSING` is placed in dataclass definitions
- Missing semantics were not correctly propagating to children
- More consistent behavior when `tyro.MISSING` is used inside of struct types
- For example: `field: tuple[DataclassA, DataclassB] = (tyro.MISSING, tyro.MISSING)`
- This was previously throwing an error
=> Consistency improvements for `tyro.MISSING`

src/tyro/_arguments.py, src/tyro/_fields.py, tests/test_dcargs.py, tests/test_py311_generated/test_dcargs_generated.py, tests/test_py311_generated/test_torch_exclude_py313_generated.py, tests/test_torch_exclude_py313.py
Adjusts behavior for unannotated arguments. For example, this is now supported:
```python
import tyro
def main(x=3, y="hello", z=(1, 2, 3)):
print(x, y, z)
tyro.cli(main)
```
It becomes:
```
usage: pr285.py [-h] [--x INT] [--y STR] [--z [INT [INT ...]]]
╭─ options ───────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
│ --x INT                 (default: 3)                    │
│ --y STR                 (default: hello)                │
│ --z [INT [INT ...]]     (default: 1 2 3)                │
╰─────────────────────────────────────────────────────────╯
```
Also fixes #282
=> Treat unannotated arguments as `Any`

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/mypy.yml, .github/workflows/publish.yml, .github/workflows/pyright.yml, .github/workflows/pytest.yml, .github/workflows/ruff.yml, CLAUDE.md, pyproject.toml, tests/conftest.py, tests/test_new_style_annotations_min_py39.py, tests/test_py311_generated/test_new_style_annotations_min_py39_generated.py
Closes #278 .
Passes Ruff checks in all environments.
Passes Pyright analysis in `dev-nn` environments < Python 3.13.
Test suite passes in all environments.
Sizes:
```text
$ du -hs venv-3.10/lib/python3.10/site-packages
139M    venv-3.10/lib/python3.10/site-packages
$ du -hs venv-3.13/lib/python3.13/site-packages
137M    venv-3.13/lib/python3.13/site-packages
$ du -hs venv-nn-3.10/lib/python3.10/site-packages
6.0G    venv-nn-3.10/lib/python3.10/site-packages
$ du -hs venv-nn-3.13/lib/python3.13/site-packages
204M    venv-nn-3.13/lib/python3.13/site-packages
```
A bit messier than I had hoped. Imports being used in module-level class definitions prevented use of `pytest.mark.skipif` as I had hoped. And using it where it could be used (in conjunction with `try .. except ImportError`) made …
=> Development: Push neural net packages and NumPy into a separate optional dependency group to reduce wait on cold setup.

src/tyro/_strings.py, tests/test_helptext.py, tests/test_py311_generated/test_helptext_generated.py
Helptext for this example was previously failing for the `Literal` and `bool` types:
```python
from typing import Literal
import tyro
type SingleOrPair[T] = tuple[T] | tuple[T, T]
def main(
x_int: SingleOrPair[int] = (1,),  # OK
x_literal: SingleOrPair[Literal[0, 1, 2]] = (0,),  # Not OK
x_bool: SingleOrPair[bool] = (True,),  # Not OK
):
pass
tyro.cli(main)
```
We were getting:
```
usage: bool_help_edge.py [-h] [--x-int INT|{INT INT}] [--x-literal {{0,1,2,0,1,2} {0,1,2}}] [--x-bool {{True,False,True,False} {True,False}}]
╭─ options ───────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
│ --x-int INT|{INT INT}   (default: 1)                    │
│ --x-literal {{0,1,2,0,1,2} {0,1,2}}                     │
│ …
```
=> Fix helptext edge case for unions of tuples of Literals

src/tyro/_resolver.py, src/tyro/constructors/_primitive_spec.py, tests/test_new_style_annotations_min_py312.py, tests/test_py311_generated/test_new_style_annotations_min_py312_generated.py
Our logic for detecting recursive types had some edge cases. Here's an example:
```python
import tyro
type MaybeTuple[T] = T | tuple[T, ...]
tyro.cli(MaybeTuple[int] | MaybeTuple[str])  # Should be ok, but was raising a runtime error.
```
The error was caused by the way we mutate sets of "seen" types. After fixing, the script above produces this CLI interface: 
```
usage: example.py [-h] INT|{[INT [INT ...]]}|STR|{[STR [STR ...]]}
╭─ positional arguments ────────────────────────────╮
│ INT|{[INT [INT ...]]}|STR|{[STR [STR ...]]}       │
│                   (required)                      │
╰───────────────────────────────────────────────────╯
╭─ options ─────────────────────────────────────────╮
│ -h, --help        show this help message and exit │ …
```
=> Fix recursive type detection edge case for type aliases

pyproject.toml, src/tyro/constructors/_backtracking.py, tests/test_collection_union_collections.py, tests/test_dcargs.py, tests/test_py311_generated/test_collection_union_collections_generated.py, tests/test_py311_generated/test_dcargs_generated.py
Reproduction:
```python
import tyro
tyro.cli(list[str], args=["a"] * 1000)
```
=> Fix argument length limit from recursive backtracking

src/tyro/_cli.py, src/tyro/_parsers.py, src/tyro/_resolver.py, tests/test_conf.py, tests/test_py311_generated/test_conf_generated.py
Fixes an edge case flagged in #328. Thanks @mirceamironenco for spotting this!
In cases like this:
```python
@tyro.conf.configure(
tyro.conf.arg(constructor_factory=lambda: AdamConfig | SgdConfig)  # type: ignore
)
@dataclasses.dataclass
class OptimizerConfig:
lr: float
@dataclasses.dataclass
class AdamConfig(OptimizerConfig):
betas: tuple[float, float]
@dataclasses.dataclass
class SgdConfig(OptimizerConfig):
fused: bool
tyro.cli(AdamConfig)
```
The problem was:
- Type analysis for subclasses requires traversing the inheritance hierarchy
- We resolve type parameters and aliases along the way
- `constructor_factory=` fields are internally treated similarly to aliases, which was causing `OptimizerConfig` to be interpreted as `AdamConfig | SgdConfig`
- This was causing runtime errors
=> Fix + tests for inheritance regression when `tyro.conf.configure()` is used

src/tyro/_cli.py, src/tyro/extras/_base_configs.py, src/tyro/extras/_subcommand_app.py, src/tyro/extras/_subcommand_cli_from_dict.py, tests/test_add_help.py
This is useful especially when we need multiple `tyro.cli()` calls, like in #296.
=> Add `add_help: bool` argument, tests

src/tyro/conf/_mutex_group.py, tests/test_mutex_groups.py, tests/test_py311_generated/test_mutex_groups_generated.py
Mutex groups are currently only supported for individual arguments, but this wasn't clear from the docs. It's possible that we'll expand the features here in the future, but in the meantime I added a note to clarify the existing behavior.
cc #129, thanks @jungerm2 for raising this!
=> Update docs, tests to clarify current mutex group behavior
